<<<<<<< HEAD
import { Outfit, Ovo } from "next/font/google";
=======
import { Outfit,Ovo } from "next/font/google";
>>>>>>> 156553d4870ec6e93b3fb8ebb640fcda7fd2e94d
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});


export const metadata = {
  title: "Portfolio - Manjunath",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" className="scroll-smooth dark">
<<<<<<< HEAD
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
=======
>>>>>>> 156553d4870ec6e93b3fb8ebb640fcda7fd2e94d
      <body
        className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden dark:bg-[#11001F] dark:text-white`}>
        {children}
      </body>
    </html>
  );
}

export default RootLayout
